const PAGES = {
  MAIN_PAGE_URL: 'https://jqueryui.com/',
};

const EXPECTED = {
  MAIN_BROWSER_TITLE: 'jQuery UI',
  DRAGGABLE_BROWSER_TITLE: 'Draggable | jQuery UI',
  UI_SELECTED: 'ui-selected',
};

const ACTION_PARAMETERS = {
  DRAGGABLE_COORDS_X: 120,
  DRAGGABLE_COORDS_Y: 120,
  RESIZABLE_COORDS_1_X: 135,
  RESIZABLE_COORDS_1_Y: 0,
  RESIZABLE_COORDS_2_X: 0,
  RESIZABLE_COORDS_2_Y: 185,
  RESIZABLE_COORDS_3_X: -35,
  RESIZABLE_COORDS_3_Y: -35,
};

export { PAGES, EXPECTED, ACTION_PARAMETERS };
